[envsec]  list by path
jetpack-io/opensource pull request #123
Opened 2023-09-01 00:09 UTC by mohsenari

## Summary
Added a check to see if user is authenticated with jetpack cloud, that means the parameter store keys follow `jetpack-data/env/org/project/<dev or prod>/name` convention. So we can reduce the number of aws API calls from 2 in case of list by tags to 1 and use getparametersByPath.

## How was it tested?
Not fully tested yet

2023-09-02 05:06 UTC, mohsenari commented on envsec/parameter_store.go
> +func envNameAndKeyFromPath(s string) (string, string) {
returns `dev, testkey1` from `/jetpack-data/env/test_org_123/proj_01h8ynw132fdytr9hagq2xngp8/dev/testkey1`

2023-09-04 23:50 UTC, mikeland73 requested changes
@mohsenari lets sync up on this. I would suggest a different approach:

* Envsec should be configurable so that the varPath function is modifiable via a constructor arg.  (This was done in https://github.com/jetpack-io/opensource/pull/122)
* The default implementation of envsec does not modify varPath function. It can listByPath **if possible** because it knows the structure.
* The **if possible** is because we need to ensure `envID` has enough parts to search by path. i.e. it must have all prefixes of path, so no empty spaces can exist in the path. If there's a gap in the path, we need to search by tags.
* If a custom varPath function is passed into `newSSMStore` then the store should fallback to listByTags.

This approach makes envsec independent from jetpack authentication and allows opensource users to take advantage of the performance optimizations of this approach. It also makes the library itself more efficient, instead of just the CLI.

2023-09-04 23:50 UTC, mikeland73 commented on envsec/envsec.go
> +	ListByPath(ctx context.Context, envId EnvId, envNames []string) (map[string][]EnvVar, error)
Instead of adding a new function, `List` should default to `listByPath`

2023-09-04 23:50 UTC, mikeland73 commented on envsec/envsec.go
> +	SecretKey    string
AWS calls this `AWS_SECRET_ACCESS_KEY`. Any reason for change

2023-09-11 15:44 UTC, closed without merging